### ISSUE TITLE
공연장 상세페이지 구현

### ISSUE THREAD

**Issue by jsh3418** [jazz-meet/jazz-meet-admin#18]
## Feature 
공연장 상세페이지 구현

## Tasks
- [x] 공연장 상세페이지 UI
- [x] 공연장 상세페이지 데이터 요청
- [x] 목록, 수정 버튼 연결
- [x] 공연장 목록 클릭시 공연장 상세보기로 연결
- [x] 공연장 수정 성공시 해당 공연장 상세보기로 이동
